apiVersion: v1
kind: Service
metadata:
  name: flightsloadbalancer
  labels:
    app: flights
spec:
  type: LoadBalancer
  selector:
    app: flights
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 50052